AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CustomResourceStack:
    Type: String

Resources:
  Example:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub ${CustomResourceStack}-ExampleCustomARN
